name: protdiff
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - jupyter_client
  - python_abi=3.8
  - jupyterlab
  - numpy==1.19
  - setuptools-git[version='>=1.2']
  - cudatoolkit=11.3
  - pip==20.1.1
  - python=3.8.5
  - openssl
  - wget
  - pytorch=1.12
  - jupyter
  - torchaudio
  - ca-certificates
  - cloudpickle==1.6.0
  - pandas~=1.1.5
  - nodejs
  - torchvision
  - jupyterlab-git
  - certifi
  - sqlite=3.33.0
  - scikit-image
  - joblib==0.14.1
  - py-xgboost==1.3.3
  - wheel=0.35.1
  - pillow==6.2.1
  - gcc_linux-64==7.3.0
  - black
  - tqdm
  - transformers=4.11.3
  - gpustat
  - matplotlib
  - pytorch-lightning=1.6.4
  - seaborn
  - conda-forge::gitpython
