name: protdiff
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python=3.8
  - conda-forge::numpy==1.19
  - conda-forge::pandas~=1.1.5
  - pytorch::pytorch=1.12
  - huggingface::transformers=4.11.3
  - conda-forge::pytorch-lightning=1.6.4
  - conda-forge::tqdm
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::mpl-scatter-density
  - conda-forge::astropy
  - conda-forge::gitpython
