description: Initial full run of CATH dataset

target:
  service: sing  # Target service platform
  name: msrresrchvc  # reference to cluster and its corresponding fields
  workspace_name: msrresrchws  # AML workspace name to use

environment: # https://singularitydocs.azurewebsites.net/docs/container_images/
  image: amlt-sing/pytorch-1.11.0
  # core packages
  # numpy - included
  # pandas - included
  # tqdm - included
  # matplotlib - included
  # seaborn - installed here
  # mpl-scatter-density - installed here
  # astropy - installed here
  # pytorch - included
  # pytorch lightning - installed here 
  # transformers - installed here
  setup:
    - pip install seaborn  # https://seaborn.pydata.org/installing.html
    - pip install mpl-scatter-density  # https://github.com/astrofrog/mpl-scatter-density
    - pip install astropy  # https://docs.astropy.org/en/stable/install.html
    - pip install transformers==4.11.3  # https://huggingface.co/docs/transformers/installation
    - pip install pytorch-lightning==1.6.4  # https://www.pytorchlightning.ai/
    - pip install sequence-models  # https://github.com/microsoft/protein-sequence-models
    - pip install biopython

code:
  local_dir: $CONFIG_DIR/..  # elative to config file directory

jobs:
- name: cath_full_run  # Unique name for each job
  sku: 16G4-V100 # 16G4-P100 = 16GB memory (these may be more free), 4 GPU P100 (16GB VRAM); G1 = any 1 GPU, 8C1 = 8 GB ram, 1 core; 80G1-A100 = A100 GPU, run amlt target list singularity -v
  priority: high
  sla_tier: premium
  command:
  - python bin/train.py config_jsons/full_run.json -o $$AMLT_OUTPUT_DIR/results